### ISSUE TITLE
No premiere features in Emby app (Android)

### ISSUE THREAD

**Issue by john8999** [nvllsvm/emby-unlocked#2]
I just applied this patch while upgrading Emby from 3.2.26.0 to 3.2.27.0. The admin panel shows the "Thank you for supporting Emby." badge and I haven't seen any nags in the webinterface yet, great!

However I still don't get any premiere features in the Android app, just trying to play any media shows the in-app nag screen. I already deleted and reinstalled the app to ensure there was nothing cached or anything.

Would you consider adding support for premiere features in the apps?

Thank you.

**Comment by nvllsvm** [comment]
Noticed this as well. Need to investigate more.

Related - the Android app is no longer open source. I'm planning on releasing the latest app open source version without the bullshit limitations.

**Comment by karelvanhecke** [comment]
Seems like the issue exists for other apps, like the windows application as well.
v3.2.27.0: dashboard shows "thank you for supporting Emby" and no nagging about premiere features, though the two apps (android and windows) that I've tested don't work.

**Comment by nvllsvm** [comment]
If their Android app is anything like https://tv.emby.media/ , it will phone home to their mb3admin.com server to validate Emby Premier status.

...so fuck them. Their Android app is closed source now, but was once GPLv2. I'm going to try to get it working and release it on F-Droid and the Play Store.
https://github.com/nvllsvm/emby-android

**Comment by RaymondSchnyder** [comment]
What the fuck is in the heads of the emby devs... they just destroy all they have done.
Thank you very much for releasing it opensource.

**Comment by majorcyto** [comment]
This is literally JUST like Plex back in the day. But to be fair Emby core team probably was like:
"Well Plex survived in the end and made money so it'll be fine!"

Except back then it was _only_ plex lol. But anyways, just like Plex there is now an open source unlocked branch. Meh.

Thanks for doing this by the way nvllsvm! Patch worked fine for me on Linux.

**Comment by majorcyto** [comment]
P.S - With this patch I can connect to my Emby server via the iOS app.

**Comment by droserasprout** [comment]
Hey, @nvllsvm!
There's a way to get full-featured Emby for Android app. I've used Lucky Patcher 7.0.4, applied Remove License Verification -> Auto Mode patch and all premium features are available now. Since Android app is now not under GPL it doesn't seem like a very legal way, but just FYI.

**Comment by droserasprout** [comment]
Worked for me with version 2.9.76. 4pda user Alex0047 managed to unlock [version 2.9.86](https://4pda.ru/forum/index.php?s=&showtopic=885885&view=findpost&p=70116502) somehow, but I don't know any of the details - automatic patching with Lucky Patcher was fixed in the next Emby update (unlike rubbish performance and thousands of bugs lol).

**Comment by Tthecreator** [comment]
Wow thanks a lot @droserasprout for you quick reaction. The forum post you send had broken download links, but I managed to get the 2.9.76 version from someplace else. I've patched it with lucky patcher and still got only 28% percent luck. So that stops there. I've now found this version here: https://apkgeek.net/emby-android/ kinda sketchy but it does work kinda. I'm still having trouble actually downloading content to my device. It's just stays queued. Do you have the same problem or is this just something I'll have to find a fix for?

**Comment by nvllsvm** [comment]
Someone can either fork one of the last open versions of the app (https://github.com/nvllsvm/emby-web-mobile) or build a new one. 

The recent Play Store builds authenticate with the Emby-owned servers.

Closing.

**Comment by Kiina** [comment]
Wouldn't it be easier for the whole project just to build a licensing server that returns valid for all requests? Change your DNS so mb3admin.com points to this server, trust the self signed cert and all features and problems will be gone? Or am I missing a big part here? I think the validation just returns a simple json.

**Comment by RaymondSchnyder** [comment]
@Kiina You are missing the part that this method you are describing is illegal.
