### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by NerdPotato** [nvllsvm/emby-unlocked#30]
Very little documentation is provided in order for any users to install this.

I've managed to find where connectionmanager.js is located, however, I haven't found any hint on where I would be able to find where to patch PluginSecurityManager. 

I would appreciate any help on how to install this, and would like documentation on how to do any of this.

I really appreciate your work, and I hope you keep doing exactly what you're doing.

**Comment by flexy123** [comment]
I "installed" this a few days ago here on my Win machine, that is I am recompiling it with Visual Studio 2017.
The patch itself is "simple", I hand-patched this since the patch shows clearly what to add and what to strip from the original...so it's not too complex. (I didn't find a properly working "patch" utility for Windows and was too lazy to install MingGW or whatever just for this measly patch).

As for connectionmanager.js, there are several instances of if in the Emby archive (6 or so, they're all identical). It's also relatively straight-forward since you only have to replace these with the changed one.

While I personally think that "patch" is not too difficult to do by hand, I admit it DOES require some expertise...afterall I am recompiling this with Visual Studio and not everyone might be familiar with it.

So or so...the Pluginsecuritymanager.cs" is ALSO part of the official Emby distribution, in the folder Emby.Sever.Implementation.Security and MediaBrowser.Model.Entities. And since this is a .CS (c sharp) source file you will have to recompile emby. (Get Visual Studio 2017, download emby distribution from Github, apply these patches, and then "build" using Visual Studio).

**Comment by NerdPotato** [comment]
Where can the connectionmanager.js be found in the emby repo?

**Comment by flexy123** [comment]
Get the (free) tool "Agentransack", it's one of the essentials I am using on all of my PCs. (I am also using this *often* when I code). Right click repo folder (or start Agentransack directly) and specify "subfolders" to search as well. Search for file location. It shows where it is. It is 5-6x in the repo. AgentRansack also allows searching for contents *within* files.

**Comment by flexy123** [comment]
D:\Repos\Emby\MediaBrowser.WebDashboard\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js
D:\Repos\Emby\MediaBrowser.WebDashboard\bin\x64\Release\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js
D:\Repos\Emby\MediaBrowser.Tests\bin\x64\Release\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js
D:\Repos\Emby\MediaBrowser.ServerApplication\bin\x64\Release\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js
D:\Repos\Emby\MediaBrowser.Server.Mono\bin\x64\Release\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js
D:\Repos\Emby\Emby.Server.Implementations\bin\x64\Release\dashboard-ui\bower_components\emby-apiclient\connectionmanager.js

**Comment by nvllsvm** [comment]
Build instructions for Alpine Linux can be found here https://github.com/nvllsvm/emby-unlocked/blob/master/docker/build.sh

For anything else, you're on your own.
